### PR TITLE
Added minor changes to pad function

### PR DESCRIPTION
**Pull request by amis-shokoohi**

### CODE REVIEW

**Comment by mcollina** [comment]
Why this change? The ifs are on purpose to avoid a loop.

**Comment by amis-shokoohi** [comment]
why?
Is there performance cost in loops?

**Comment by amis-shokoohi** [comment]
why?
Is there performance cost in loops?

**Comment by mcollina** [comment]
Yes exactly. Your solution also allocates a lot of strings that are not needed.

**Pull request closed without merging**
