### PR TITLE
Add fastest and slowest to benchmark

### PR DESCRIPTION
**Pull request by woss**
- [x] Add fastest and slowest to benchmarks
- [x] upgrade packages
- [x] improve actions CI workflow

### CODE REVIEW

**Comment by woss** [comment]
this PR includes the formatting of benchmarks js file and package.json natural sorting

**Review by mcollina — CHANGES_REQUESTED** [review]
please restore the old linting

**Comment by woss** [comment]
@mcollina done

**Comment by woss** [comment]
i'm not going to change the benchmarks in the README.md since I have a better machine than what's tested on. 
here are my measurements
```
time node benchmark.js
crypto.randomUUID x 25,506,688 ops/sec ±0.85% (95 runs sampled)
hashids process.hrtime x 630,074 ops/sec ±0.84% (94 runs sampled)
hashids counter x 1,311,605 ops/sec ±1.11% (91 runs sampled)
shortid x 81,789 ops/sec ±1.88% (90 runs sampled)
crypto.random x 680,411 ops/sec ±1.49% (92 runs sampled)
nid x 1,342,997 ops/sec ±0.34% (95 runs sampled)
uuid.v4 x 2,464,305 ops/sec ±0.48% (95 runs sampled)
napiRsUuid.v4 x 6,052,699 ops/sec ±1.16% (98 runs sampled)
uuid.v1 x 3,320,904 ops/sec ±0.65% (98 runs sampled)
nanoid x 5,712,351 ops/sec ±6.12% (88 runs sampled)
hyperid - variable length x 38,822,129 ops/sec ±1.28% (91 runs sampled)
hyperid - fixed length x 39,178,669 ops/sec ±0.43% (99 runs sampled)
hyperid - fixed length, url safe x 39,907,360 ops/sec ±0.74% (94 runs sampled)


Fastest is hyperid - fixed length, url safe
Slowest is shortid
user=70.17s system=1.29s cpu=92% total=1:17.66
```

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by woss** [comment]
@mcollina can you please provide the prettier and eslint configs? it would be useful for contributors

**Comment by woss** [comment]
@mcollina i've updated the ci.yaml. it seems that nullish coalescing operator is added in 14 + based on https://stackoverflow.com/a/68692190/2764898 

I tested `legacy` command on 13 and it works whereas the normal test fails. the last commit should work.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
the legacy script is missing.

**Comment by woss** [comment]
damn it, i was 100% sure i committed the package.json. must have been tired.

**Comment by mcollina** [comment]
Can you remove 0.10, 0.12 and 4, those were never supported here

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by woss** [comment]
@mcollina please don't forget to update the README with the benchmarks ran on your hardware

**Pull request merged**
