### PR TITLE
add startFrom to opts interface

### PR DESCRIPTION
**Pull request by yonathan06**
adding `opts.startFrom` to typings

### CODE REVIEW

**Comment by mcollina** [comment]
Can you also add the option to https://github.com/mcollina/hyperid/blob/master/test/example.ts?

**Comment by yonathan06** [comment]
@mcollina done

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by yonathan06** [comment]
I don't have write access to this repo, so need someone who does to merge this PR

**Pull request merged**
